version: '3.1'

services:

  django:
    build:
      context: ./
      dockerfile: ./Dockerfiles/django/Dockerfile
    restart: unless-stopped
    entrypoint: /django-launcher.dev.sh
    volumes:
      - .:/usr/src/app/
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: ""
      SECRET_KEY: ""
      DB_ENGINE: "django.db.backends.sqlite3"
      DB_NAME: "database.sqlite"
      DB_USER: ""
      DB_PASSWORD: ""
      DB_HOST: ""
      DB_PORT: ""
      DOMAIN: "ejemplo.localhost"
      DOMAIN_URL: "http://ejemplo.localhost"
      STATIC_URL: "/static/"
      STATIC_ROOT: "static"
      MEDIA_URL: "/media/"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      EMAIL_HOST: "mailhog"
      EMAIL_USE_TLS: "False"
      EMAIL_PORT: "1025"
      EMAIL_USER: ""
      EMAIL_PASSWORD: ""
    expose:
      - 8000

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./Caddyfile.dev:/etc/caddy/Caddyfile
        - ./../caddy_data:/data
        - .:/usr/src/app/
    depends_on:
      - django
      
  redis:
    image: redis:alpine
    restart: unless-stopped
    expose:
      - 6379

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    expose:
        - 1025
    ports:
        - 8025:8025
