version: '3.1'

services:

  django:
    build:
      context: ./
      dockerfile: ./Dockerfiles/django/Dockerfile
    restart: always
    entrypoint: /django-launcher.dev.sh
    volumes:
      - .:/usr/src/app/
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: ""
      SECRET_KEY: "secret"
      DB: "database.sqlite"
      DOMAIN: ""
      DOMAIN_URL: "https://"
      STATIC_URL: "/static/"
      STATIC_ROOT: "static"
      MEDIA_URL: "/media/"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      EMAIL_HOST: ""
      EMAIL_USE_TLS: "True"
      EMAIL_PORT: "2525"
      EMAIL_USER: ""
      EMAIL_PASSWORD: ""
    expose:
      - 8000

  caddy:
    image: caddy:alpine
    restart: always
    ports:
        - 80:80
        - 443:443
    volumes:
        - .:/usr/src/app/
        - ./Caddyfile.staging:/etc/caddy/Caddyfile
        - ./../caddy_data:/data
    depends_on:
      - django
      
  redis:
    image: redis:alpine
    restart: unless-stopped
    expose:
      - 6379

  gulp:
    build: Dockerfiles/gulp
    restart: always
    command: gulp
    volumes:
        - .:/app/
    depends_on:
      - caddy
