version: '3.1'

services:

  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sapps
    ports:
      - 5432:5432

  django:
    build:
      context: ./
      dockerfile: ./Dockerfiles/django/Dockerfile
    restart: always
    entrypoint: /django-launcher.dev.sh
    volumes:
      - .:/usr/src/app/
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: ""
      SECRET_KEY: "secret"
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: "sapps"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "postgresql"
      DB_PORT: "5432"
      DOMAIN: "ejemplo.com"
      DOMAIN_URL: "https://ejemplo.com"
      STATIC_URL: "/static/"
      STATIC_ROOT: "static"
      MEDIA_URL: "/media/"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      EMAIL_HOST: ""
      EMAIL_USE_TLS: "True"
      EMAIL_PORT: "2525"
      EMAIL_USER: ""
      EMAIL_PASSWORD: ""
    expose:
      - 8000
    depends_on:
      - postgresql

  caddy:
    image: caddy:alpine
    restart: always
    ports:
        - 80:80
        - 443:443
    volumes:
        - .:/usr/src/app/
        - ./Caddyfile.staging:/etc/caddy/Caddyfile
        - ./../caddy_data:/data
    depends_on:
      - django
      
  redis:
    image: redis:alpine
    restart: unless-stopped
    expose:
      - 6379

  gulp:
    build: Dockerfiles/gulp
    restart: always
    command: gulp
    volumes:
        - .:/app/
    depends_on:
      - caddy
