version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./../postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kualitte
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  django:
    build:
      context: .
      dockerfile: ./Dockerfiles/django/Dockerfile
    restart: always
    entrypoint: /django-launcher.dev.sh
    volumes:
      - .:/usr/src/app/
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: "beta.neo.kualitteauctions.com"
      SECRET_KEY: "mysecret"
      DB_HOST: db
      DB_NAME: "kualitte"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_PORT: "5432"
      DOMAIN: "beta.neo.kualitteauctions.com"
      DOMAIN_URL: "https://beta.neo.kualitteauctions.com"
      STATIC_URL: "/static/"
      MEDIA_URL: "/media/"
      EMAIL_HOST: "mailhog"
      EMAIL_USE_TLS: "False"
      EMAIL_PORT: "1025"
      EMAIL_USER: ""
      EMAIL_PASSWORD: ""
    expose:
      - 8000
    depends_on:
      - db

  caddy:
    image: caddy:alpine
    restart: always
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./../caddy_data:/data
        - .:/usr/src/app/
    depends_on:
      - django

  gulp:
    build:
      context: .
      dockerfile: ./Dockerfiles/gulp/Dockerfile
    restart: always
    command: gulp
    volumes:
        - ./gulpfile.js:/usr/src/app/gulpfile.js
        - ./assets:/usr/src/app/assets
        - ./static:/usr/src/app/static
    depends_on:
      - caddy
